stages:
  - 🧪 test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=./.m2/repository"

cache:
  paths:
    - ./.m2/

test:
  stage: 🧪 test
  image: maven:3-jdk-11
  coverage: '/Total.*?([0-9]{1,3})%/'
  script:
    - mvn $MAVEN_OPTS test jacoco:report
    - cat target/site/jacoco-ut/index.html